name: lint-check

run-name: lint checking...

on:
  pull_request:
    branches: development

jobs:
  check-lint-errors:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn

      - name: run lint
        run: yarn lint
