name: lint-check

run-name: lint checking...

on: [push]

jobs:
 
  check-lint-errors:
   
   runs-on: ubuntu-latest

   steps: 

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
    - name: Use node.js
       with:
         node-version: '20.x'

    - name: Install dependencies
    - run : yarn

    - name: run lint
    - run: yarn lint


