name: GITHUB ACTIONS TRIAL
run-name: ${{github.actor}} is testing out github actions

on: [push]

jobs:
  Explore-github-actions:
   runs-on: ubuntu-latest
   steps:
     - run: echo " the job was automatically triggered by a ${{github.event_name}} event"
     - run: echo "the name of branch is ${{github.ref}} and repository ${{github.repository}}"
 
