name: version update and auto release

run-name: version update and auto-release

on:
  push:
    branches:
      - main

jobs:
  version-bump-up:
   runs-on: ubuntu-latest
   steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          persist-credentials: false
          token: ${{secrets.GITHUB_TOKEN}}

      - name: install dependencies
        run: yarn

      - name: set up git and authenticate
        run: |
          git config --global user.email "shrilakshmishastry@gmail.com"
          git config --global user.name "shrilakshmishastry"  
         
         
      - name: version bump up
        run: yarn version --new-version minor

      - name: checkout to a new branch 
        run: |
          git checkout -b pr-merge-to-develop-temp-branch
          git add .
          git commit -m "chore: release new tag "
          git push origin pr-merge-to-develop-temp-branch

      - name: rise PR and merge
        uses: peter-evans/create-pull-request@v3
        with: 
         token: ${{secrets.GITHUB_TOKEN}}
         commit-message: "Automated pull request creation"
         title: "Update the main branch"
         body: "Automatically updating the main branch via GitHub Actions"
         branch: pr-merge-to-develop-temp-branch
         base: main
        
         

      - name: push changes and create the tag
        run: |   
          git push --tags

      - name: delete temp branch
        run: git branch -D pr-merge-to-develop-temp-branch
     

