name: version update and auto release

run-name: version update and auto-release

on:
  push:
    branches:
      - main

jobs:
  version-bump-up:
   runs-on: ubuntu-latest
   steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
             token: ${{secrets.GITHUB_TOKEN}} 
        
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
         
      - name: Install Yarn
        run: | 
             npm install 
             npm install -g yarn@1.22.19
             yarn version
             npm version


     
             
      - name: install dependency
        run: yarn

      - name: set up git and authenticate
        run: |
          git config --global user.email "shrilakshmishastry@gmail.com"
          git config --global user.name "shrilakshmishastry"  
      
             
      - name: version bump up
        run: |
            yarn version --minor
            cat package.json  
      
      - name: create PR  
        run: |
             git checkout -b version-bump-up
             git add .
             git commit -m "chore: version bump up"
             git push origin version-bump-up

      - name: merge PR to main
       
        run: |
             git checkout main
             git merge version-bump-up
        
              

      - name: push changes and create the tag
        run: |   
          git push --tags
