name: version update and auto release

run-name: version update and auto release

on:
  push:
    branches:
      - main

jobs:
  version-bump-up:
   runs-on: ubuntu-latest
   steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: install dependencies
        run: yarn

      - name: set up git
        run: |
          git config --global user.email "shrilakshmishastry@gmail.com"
          git config --global user.name "shrilakshmishastry"  

      - name: Authenticate with GitHub package registry
         with:
          persist-credentials: false
          token: ${{secrets.GITHUB_TOKEN}}

      - name: version bump up
        run: yarn version patch

         

      - name: push changes and create tag
        run: |   
          git push --follow-tags origin HEAD:refs/heads/main
          git push --tags

